### PR TITLE
Allow to control emulator's video mode

### PR DESCRIPTION
**Pull request by martyone**
After all the refactorization done with the first two commits in not really needed, but it took some time to find the error so good to record it..

### CODE REVIEW

**Comment by JussiPakkanen** [comment]
QMap<QString, QSize> MerEmulatorDevice::availableDeviceModels() const
    {
        static QMap<QString, QSize> modes {
            { tr("Jolla Phone"), QSize(540, 960) },
            { tr("Jolla Tablet"), QSize(1536, 2048) },
        };
        return modes;
    }

Shouldn't this return const QMap<QString, QSize>& instead? Or not define the modes variable as static. Currently it always creates a full copy on every method call.

There are a few uses of the auto keyword. Testing on the build machine says that its gcc (4.4.4) does have c++0x and that the build uses it. Once the trial build finishes we know if it actually works.

**Comment by JussiPakkanen** [comment]
Does not compile:

https://etherpad.jollamobile.com/pastebin/1437655659/

**Comment by martyone** [comment]
It seems I never presses the green button bellow, so here is my late reply :)

> Shouldn't this return const QMap& instead? Or not define the modes variable as static. Currently it always creates a full copy on every method call.

http://doc.qt.io/qt-5/implicit-sharing.html

Also updated with the dereferencing of QPointers.

**Comment by JussiPakkanen** [comment]
The fact that Qt does implicit sharing behind the scenes is not really relevant. The point is that the function returns data that all clients should treat as const as a mutable value. This may lead to bugs where they alter the value by accident. Returning const ref makes this impossible so calling code can't do the wrong thing. If they absolutely must make a copy, they have to do that explicitly.

**Comment by JussiPakkanen** [comment]
Assuming you can do auto x = getAvailableDeviceModels(). A quick grepping says it is not used much in QtC code. It compiled on 1004 but does it work on OSX? Full c++11 support landed only in Mavericks and the build machine is mountain lion AFAICR.

**Comment by martyone** [comment]
> Returning const ref makes this impossible so calling code can't do the wrong thing. If they absolutely must make a copy, they have to do that explicitly.

That's not the "Qt way" of designing APIs :) You would get a return value of a reference type only where performance may be critical http://doc.qt.io/qt-5/qpoint.html - and only when you explicitly require it AFAIK.

**Comment by martyone** [comment]
Why is the "close and comment" button there and so big???

**Comment by martyone** [comment]
> does it work on OSX?

Let's try build it? :)

**Comment by JussiPakkanen** [comment]
If this is established Qt practice then I guess we can go with it. But at least for shared_ptr the performance cost of _not_ passing shared_ptrs by ref can be substantial: https://stackoverflow.com/questions/2502394/the-cost-of-passing-by-shared-ptr

That's probably because it uses atomics. I'm not sure if Qt's containers use those behind the scenes.

**Comment by martyone** [comment]
Yes, Qt containers use atomics http://doc.qt.io/qt-5/threads-modules.html#threads-and-implicitly-shared-classes, but I am sure we are rarely writing such a performance critical code to worry about.

> If this is established Qt practice then I guess we can go with it.

Definitely. I always look at the surrounding code first. (QtC has not the shiniest codes, though:))

**Comment by martyone** [comment]
Merge?

**Pull request merged**
