### PR TITLE
Many device models

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by martyone** [comment]
Forgot to mention: let's see if the lambda compiles with all our compilers...

**Comment by JussiPakkanen** [comment]
/home/builder/src/sailfish-qtcreator/src/plugins/mer/meremulatordevice.cpp: In constructor ‘Mer::Internal::MerEmulatorDevice::MerEmulatorDevice()’:
    /home/builder/src/sailfish-qtcreator/src/plugins/mer/meremulatordevice.cpp:188: error: expected primary-expression before ‘[’ token

So that would be a no then...

**Comment by martyone** [comment]
:\ please try now

**Comment by JussiPakkanen** [comment]
Compiles: 🖒

**Comment by JussiPakkanen** [comment]
lgtm

**Pull request merged**
